name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout o código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
      
      - name: Lançar DOCKERFILE 
        run: |
          docker build -t meu-app:latest .        
          docker run --rm meu-app:latest echo "Container rodou com sucesso" 
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout o código
        uses: actions/checkout@v3               

      - name: Configurar Python
        uses: actions/setup-python@v4
      
      - name: Instalar Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Rodar testes
        run: |
          docker-compose run api python -m unittest discover
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy render
        env:
          RENDER_API_KEY: ${{ secrets.CHAVE_DEPLOY_SECRETA }}
          RENDER_SERVICE_ID: ${{ secrets.ID_DEPLOY_RENDER_SECRETO }}
        run: |            
          curl --request POST \
          --url https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys \
          --header "Authorization: Bearer $RENDER_API_KEY" \
          --header "Content-Type: application/json" \
          --data '{}'