name: CI/CD Pipeline
#aa
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout o código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
      
      - name: Lançar DOCKERFILE 
        run: |
          docker build -t meu-app:latest .        
          docker run --rm meu-app:latest echo "Container rodou com sucesso" 
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout o código
        uses: actions/checkout@v3               

      - name: Configurar Python
        uses: actions/setup-python@v4
      
      - name: Instalar Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Rodar testes
        run: |
          docker-compose up -d
  deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
          - name: Deploy render
            env:
              RENDER_API_KEY: ${{ secrets.CHAVE_DEPLOY_SECRETA }}
              RENDER_SERVICE_ID: ${{ secrets.ID_DEPLOY_RENDER_SECRETO }}
            run: |
              curl -X POST https://api.render.com/deploy/sync \
                -H "Authorization: Bearer $RENDER_API_KEY" \
                -H "Content-Type: application/json" \
                -d '{"serviceId": "'"$RENDER_SERVICE_ID"'"}'